
create table ACCOUNTS
(
    ID               BIGINT auto_increment
        primary key,
    DATE_OF_BIRTHDAY VARCHAR(255),
    EMAIL            VARCHAR(255),
    PASSWORD         VARCHAR(255),
    PLACE            VARCHAR(255),
    USER_NAME        VARCHAR(255)
);

INSERT INTO ACCOUNTS(ID, DATE_OF_BIRTHDAY, EMAIL, PASSWORD, PLACE, USER_NAME)
VALUES ('12', '29.07.2001', 'denis@mail.ru', 'denis123', 'Западная Двина', 'DENIS');
INSERT INTO ACCOUNTS(ID, DATE_OF_BIRTHDAY, EMAIL, PASSWORD, PLACE, USER_NAME)
VALUES ('13', '09.10.2000', 'mischa@gmail.ru', 'mischa123', 'Тверь', 'MISCHA');
INSERT INTO ACCOUNTS(ID, DATE_OF_BIRTHDAY, EMAIL, PASSWORD, PLACE, USER_NAME)
VALUES ('14', '13.05.2001', 'olesya@yandex.ru', 'olesya123', 'Тверь', 'OLESYA');
INSERT INTO ACCOUNTS(ID, DATE_OF_BIRTHDAY, EMAIL, PASSWORD, PLACE, USER_NAME)
VALUES ('15', '11.07.2001', 'artem@mail.ru', 'artem123', 'Тверь', 'ARTEM');

create table HOTELS
(
    ID                     BIGINT auto_increment
        primary key,
    HOTEL_NAME             VARCHAR(255),
    ADDRESS_HOTELS_ID      BIGINT,
    WORKING_TIME_HOTELS_ID BIGINT,
    constraint FKLL2YCGVB4B8IKIRDN3NUSBWCC
        foreign key (WORKING_TIME_HOTELS_ID) references WORKING_TIME_HOTELS (ID),
    constraint FKPCJRTFV3UBSL2M1DSFELTM3VJ
        foreign key (ADDRESS_HOTELS_ID) references ADDRESS_HOTELS (ID)
);


INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('11', 'AURORA APARTMENTS на Почтамской');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('12', 'Alanda');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('13', 'Brandenburger Hof Berlin');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('14', 'Apex International');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('15', 'Boix Mar');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('16', 'Casper');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('17', 'Sweetlnd Hotel');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('18', 'Disneys Hotel Cheyenne');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('19', 'Hotel de Berne');
INSERT INTO HOTELS(ID, HOTEL_NAME)
VALUES ('10', 'Hotel Plaza Athenee');

create table ADDRESS_HOTELS
(
    ID       BIGINT not null
        primary key,
    BUILDING INTEGER,
    CITY     VARCHAR(255),
    COUNTRY  VARCHAR(255),
    STREET   VARCHAR(255)
);

INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('1', '10', 'Санкт-Петербург', 'Россия', 'Лесная ул.');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('2', '4', 'Москва', 'Россия', 'Тимирязевская ул.');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('3', '14', 'Берлин', 'Германия', 'Eislebener Strassee');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('4', '32', 'Лондон', 'Великобритани', 'Grassmarket Edinburgh');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('5', '3', 'Мадрид', 'Испания', 'C/Enric Morera');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('6', '20', 'Баку', 'Азурбайджан', 'ул. Академика Гасана Алиева');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('7', '11', 'Пекин', 'Китай', 'Tiatong Lu');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('8', '19', 'Париж', 'Франция', 'Boulevard de IErope');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('9', '37', 'Париж', 'Франция', 'Route de Chalifert');
INSERT INTO ADDRESS_HOTELS(ID, BUILDING, CITY, COUNTRY, STREET)
VALUES ('10', '10', 'Токио', 'Япония', 'Takanawa, Minato-ku');


create table WORKING_TIME_HOTELS
(
    ID                       BIGINT not null
        primary key,
    WEEKDAYS_WORKING_TIME_ID BIGINT,
    WEEKENDS_WORKING_TIME_ID BIGINT,
    constraint FKG2W1M069BAVFDMOLNU9NRSW43
        foreign key (WEEKDAYS_WORKING_TIME_ID) references WEEKDAYS_WORKING_TIME_HOTELS (ID),
    constraint FKN2HRO32IU7AMPPPU29BWGYX55
        foreign key (WEEKENDS_WORKING_TIME_ID) references WEEKENDS_WORKING_TIME_HOTELS (ID)
);



INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('1');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('2');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('3');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('4');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('5');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('6');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('7');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('8');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('9');
INSERT INTO WORKING_TIME_HOTELS(ID)
VALUES ('10');


create table WEEKDAYS_WORKING_TIME_HOTELS
(
    ID                 BIGINT not null
        primary key,
    WEEKDAYS_ENDWORK   VARCHAR(255),
    WEEKDAYS_STARTWORK VARCHAR(255)
);

INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('1', '23:00', '5:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('2', '23:00', '5:30');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('3', '22:30', '5:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('4', '23:00', '6:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('5', '0:00', '7:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('6', '0:00', '6:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('7', '23:00', '6:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('8', '23:00', '5:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('9', '23:00', '5:00');
INSERT INTO WEEKDAYS_WORKING_TIME_HOTELS(ID, WEEKDAYS_ENDWORK, WEEKDAYS_STARTWORK)
VALUES ('10', '0:00', '6:00');


create table WEEKENDS_WORKING_TIME_HOTELS
(
    ID                 BIGINT not null
        primary key,
    WEEKENDS_ENDWORK   VARCHAR(255),
    WEEKENDS_STARTWORK VARCHAR(255)
);

INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('1', '20:00', '8:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('2', '21:00', '8:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('3', '20:30', '7:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('4', '21:00', '8:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('5', '22:00', '9:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('6', '22:00', '8:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('7', '21:00', '8:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('8', '21:00', '7:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('9', '21:00', '7:00');
INSERT INTO WEEKENDS_WORKING_TIME_HOTELS(ID, WEEKENDS_ENDWORK, WEEKENDS_STARTWORK)
VALUES ('10', '22:00', '8:00');


create table ROOMS
(
    ID        BIGINT not null
        primary key,
    PRICE_ID  BIGINT,
    HOTELS_ID BIGINT,
    constraint FK29WOO7TWYSB5YYH4WYYTTM2H
        foreign key (HOTELS_ID) references HOTELS (ID),
    constraint FK2JLLY6OHRWE0P31QA25CR2MQQ
        foreign key (PRICE_ID) references PRICE_ROOMS (ID)
);

INSERT INTO ROOMS(ID)
VALUES ('1');
INSERT INTO ROOMS(ID)
VALUES ('2');
INSERT INTO ROOMS(ID)
VALUES ('3');
INSERT INTO ROOMS(ID)
VALUES ('4');
INSERT INTO ROOMS(ID)
VALUES ('5');
INSERT INTO ROOMS(ID)
VALUES ('6');
INSERT INTO ROOMS(ID)
VALUES ('7');
INSERT INTO ROOMS(ID)
VALUES ('8');
INSERT INTO ROOMS(ID)
VALUES ('9');
INSERT INTO ROOMS(ID)
VALUES ('10');


create table PRICE_ROOMS
(
    ID       BIGINT not null
        primary key,
    AMOUNT   INTEGER,
    CURRENCY VARCHAR(255)
);

INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('1', '700', 'RUB');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('2', '850', 'RUB');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('3', '10', 'EUR');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('4', '9', 'GBR');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('5', '9', 'EUR');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('6', '22', 'AZN');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('7', '78', 'CNY');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('8', '10', 'EUR');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('9', '11', 'EUR');
INSERT INTO PRICE_ROOMS(ID, AMOUNT, CURRENCY)
VALUES ('10', '11', 'JPY');

create table BEDS
(
    ID       BIGINT not null
        primary key,
    AMOUNT   INTEGER,
    CAPACITY INTEGER,
    ROOMS_ID BIGINT,
    constraint FKPMUIFHR484E09AWK53DVYBT0X
        foreign key (ROOMS_ID) references ROOMS (ID)
);


INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('1', '2', '2');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('2', '2', '4');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('3', '2', '3');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('4', '1', '1');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('5', '4', '4');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('6', '1', '2');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('7', '3', '3');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('8', '3', '4');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('9', '2', '4');
INSERT INTO BEDS(ID, AMOUNT, CAPACITY)
VALUES ('10', '1', '2');

create table COMFORTS
(
    ID       BIGINT not null
        primary key,
    NAME     VARCHAR(255),
    ROOMS_ID BIGINT,
    constraint FK3T1Q3TNV06IDK16NO3VIOFMGI
        foreign key (ROOMS_ID) references ROOMS (ID)
);

INSERT INTO COMFORTS(ID, NAME)
VALUES ('1', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('2', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('3', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('4', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('5', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('6', 'ТВ, wi-fi, джакузи');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('7', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('8', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('9', 'ТВ, wi-fi, душ');
INSERT INTO COMFORTS(ID, NAME)
VALUES ('10', 'ТВ, wi-fi, джакузи');